name: deploy-nginx
on:
  push:
    branches:
      - main
    paths:
      - helm/nginx-demo
  workflow_dispatch:
    inputs:
      realRun:
        description: 'dry run or real, default: dry-run'
        required: true
        type: boolean
jobs:
  deploy:
    runs-on: ubuntu-22.04

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'simple-autopilot-public-cluster'
        location: 'asia-southeast1'

    - id: 'get-pods'
      run: 'kubectl get pods'

    - uses: azure/setup-helm@v3
      id: install-helm

    - id: helm-upgrade
      env:
        REAL_RUN: ${{ inputs.realRun }}
      run: |
        helm upgrade --install nginx ./helm/nginx-demo --dry-run=${REAL_RUN}
